name: JeremyBrian
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.75
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3d8ad'
    - '#5a3e30'
    - '#d9b987'
    - '#b4945c'
  brandStrength: 0.625
  lightness: 0.5451024915091693
  saturation: 0.3125
  rhythmicContrast: 0.4765697412658483
purpose: []
